FROM node:16-alpine

WORKDIR /app

COPY package*.json yarn.lock ./ 
RUN apk add --no-cache yarn

RUN apk add --no-cache python3
ENV PYTHON=/usr/bin/python3

RUN apk add --no-cache make g++

RUN yarn install
COPY . ./

EXPOSE 3001

CMD ["yarn", "start"]
